# Books

For the purposes of this site, I'm defining a book as a unit of printed output. This could be a traditional printed book, but it could also be a broadside, pamphlet, news sheet, or other piece of printed ephemera. Books are distinct from texts in this schema: a book can be made up of many individual texts.

## Sample Research Questions

- Who made a book, and through what processes?
- How does digitization transform a book?
- What is lost in the process(es) of digitization?

## Tools and Websites

- [EEBO](https://about.proquest.com/en/products-services/eebo/)
- [Text Creation Partnership](https://textcreationpartnership.org/)
- [EarlyPrint Library](https://texts.earlyprint.org/exist/apps/shc/home.html)
- Internet Archive Early English Books:
  - [1475–1640](https://archive.org/details/pub_early-english-books-1475-1640?tab=collection&sort=-reviewdate)
  - [1641–1700](https://archive.org/details/pub_early-english-books-1641-1700?tab=collection)
- English Short Title Catalogue (ESTC):
  - [CERL Beta Version](https://datb.cerl.org/estc/)
  - [Print & Probability Version](https://estc.printprobability.org/)
- [Text Encoding Initiative](https://tei-c.org/)
- [English Broadside Ballad Archive](https://ebba.english.ucsb.edu/)

## Activities

### Digitization

1) Go to the Internet Archive pages for Early English Books: [1475–1640](https://archive.org/details/pub_early-english-books-1475-1640?tab=collection&sort=-downloads) or [1641–1700](https://archive.org/details/pub_early-english-books-1641-1700?tab=collection)

2) Select a topic that interests you, and search for a book that matches that topic.

3) Select a book and choose an interesting page (just one page, or even less!). For a fun challenge, you might choose a page that has more than just a single block of prose text. Maybe your page has a poem or a song. Maybe it has multiple columns, or even a table or diagram.

4) Follow the guide to create an XML representation of that page or part of the page

- Read over parts of the introduction to XML here (you only need to read v.1-3 and v.6): <https://tei-c.org/release/doc/tei-p5-doc/en/html/SG.html>. You can also use the [TEI By Example tutorial](https://www.teibyexample.org/exist/tutorials/TBED01v00.htm).
- Once you have you a sense of XML, you can mark up your text in whatever way you see fit. Feel free to make up whatever elements and attributes you like. *For a good example, look over the poem in section v.3, highlighted in pink.*
- You can use any plaintext editor for this, such as Brackets: <https://brackets.io/>.
- **Ask lots of questions.** Again, the goal is to get a feel for how this works rather than create a perfect object. If your page is very long, you can choose just one part to represent.

5) Think about what is gained and what is lost in this representation vs. the digital image vs. the physical book itself (which you've never seen!).

6) Compare your XML to the TCP version and the EarlyPrint version. You can find both at: <https://earlyprint.org/download>

## References

- @siefring_sustaining_2013
- @quiring_fingerprints_2024
- @trettien_cutcopypaste_2022
- @mclean_early_2001
- @kichuk_metamorphosis_2007
- @martin_eebo_2007
- @gadd_use_2009
- @vogler_clustering_2024
- @warren_who_2023
- @warren_damaged_2020
- @smith_all_2023
